### ISSUE TITLE
{:tcp, ...} message sent to wrong process when using async

### ISSUE THREAD

**Issue by vishnevskiy** [benoitc/hackney#224]
I had this problem on hackeny 1.1.0 and hoped it would be fixed by upgrading to 1.3.1 but still occurring. I don't have a repro case and it just occurs randomly in production.

Basically I have a process that uses hackney to watch etcd node changes and it will randomly stop doing anything and in my log I will have a "Unexpected message: {:tcp, #Port<0.2975>, etc..." so it means its somehow hitting another process in my system that has that handle_info defined.

Any ideas?

**Comment by benoitc** [comment]
do you have any message before ? can you share a snippet of code?

**Comment by vishnevskiy** [comment]
https://gist.github.com/vishnevskiy/22b0cf68593320ce075a

That is the code of the process that is having a problem.
Looks like "Unexpected message: " is within the hackney code.

**Comment by vishnevskiy** [comment]
Any ideas? :(

**Comment by benoitc** [comment]
i am woring on an update this we. should land on monday anyway.

- benoît

**Comment by vishnevskiy** [comment]
Thank you, looking forward to it.

**Comment by benoitc** [comment]
Are you using a proxy? I wonder if it's not the same issue found in #223 ?

**Comment by benoitc** [comment]
Also could you test witht the latest master ?

**Comment by vishnevskiy** [comment]
I was not using a proxy. Would this have any effect on master still?

**Comment by benoitc** [comment]
i am not sure. the message come from the hackney_stream module. However I added a way to trace it in the latest master. Maybe you could try to reproduce it with the trace enabled?  To enable the trace you can do it somwhere in your code or in the shell by running the following command line:

    hackney_trace:enable(max, io)

**Comment by vishnevskiy** [comment]
Alright I will try it out in our next release.

**Comment by benoitc** [comment]
@vishnevskiy ok let me know. I think it is solved in current master. I will release the 1.3.2 today anyway.

**Comment by benoitc** [comment]
bump

**Comment by vishnevskiy** [comment]
Sorry have not had a chance to deploy to prod due to busy last 2 weeks. I will get back to you about this as soon as I can.

**Comment by vishnevskiy** [comment]
Looks like someone else changed it so we don't use async and just have another process do a blocking call to resolve the problem and that is in prod now. I was only able to repro this bug before on prod due to the high concurrency of things going on. I am probably not going to be able to do that without reverting our code. Feel free to close this if no one else is reporting it.

**Comment by benoitc** [comment]
@vishnevskiy ok no pb.

Anyway I am pretty sure that the issue has been solved in last stable release. Also the problem will definitely go in next release with the connections supervision improvement. So closing the issue.

**Comment by flupke** [comment]
I still encounter this bug in production with hackney 1.3.2. Here is one I just had while running a test (it happens maybe on 1/10 run, it's a simple test with 1000 concurrent async queries)

```
unexpected message received: {:tcp, #Port<0.13869>, \"HTTP/1.1 200 OK\\r\\nconnection: keep-alive\\r\\nserver: Cowboy\\r\\ndate: Mon, 14 Sep 2015 17:40:44 GMT\\r\\ncontent-length: 27\\r\\ncontent-type: application/json\\r\\n\\r\\n{\\n  \\\"origin\\\": \\\"127.0.0.1\\\"\\n}\"}
```

**Comment by flupke** [comment]
Hmm sorry this is my code, I'll try removing the catch-all clause in my receive.

**Comment by flupke** [comment]
If I remove my catch-all clause it ends up with a timeout, and errors I see in production are hackney error logs:
```
Unexpected message: {tcp,#Port<0.30001>,<<255,216,255,224,0,16,74,70,73,70,0,1,2...>>}
```

**Comment by flupke** [comment]
I should be able to extract the code and make a small (Elixir) app that illustrates the bug if you want.

**Comment by benoitc** [comment]
@flupke yes please :) I will try it ASAP!

**Comment by flupke** [comment]
To reproduce:
```
git clone https://github.com/flupke/hackney_message_bug.git
cd hackney_message_bug
mix deps.get
mix test
```
Note that I don't always get the same bug, sometimes just an error log from hackney followed by a timeout in Task.await:
```
$ mix test                                                                                                                                                                                                                                 (09-16 10:38)
Starting HTTParrot on port 8080
Starting HTTParrot on port 8433 (SSL)

10:38:29.721 [error] Unexpected message: {:tcp_closed, #Port<0.22602>}



  1) test concurrent downloads of the same URL (HackneyMessageBugTest)
     test/hackney_message_bug_test.exs:41
     ** (exit) exited in: Task.await(%Task{pid: #PID<0.29689.0>, ref: #Reference<0.0.4.33018>}, 10000)
         ** (EXIT) time out
     stacktrace:
       (elixir) lib/task.ex:207: Task.await/2
       (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:537: Enum.each/2
       (elixir) lib/enum.ex:543: anonymous fn/3 in Enum.each/2
       (elixir) lib/enum.ex:1266: anonymous fn/3 in Enum.reduce/3
       (elixir) lib/range.ex:77: Enumerable.Range.reduce/6
       (elixir) lib/enum.ex:1265: Enum.reduce/3
       (elixir) lib/enum.ex:542: Enum.each/2



Finished in 13.7 seconds (0.04s on load, 13.6s on tests)
1 tests, 1 failures

Randomized with seed 625285
```
And sometimes the unexpected message reaches my code:
```
$ mix test                                                                                                                                                                                                                        (09-16 10:40)
Starting HTTParrot on port 8080
Starting HTTParrot on port 8433 (SSL)

10:43:50.517 [error] Task #PID<0.14898.5> started from #PID<0.367.0> terminating
Function: #Function<4.28562980/0 in HackneyMessageBugTest.do_ten_downloads/1>
    Args: []
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, "http://localhost:8080/ip download failed after 1 tries: unexpected message received: {:tcp, #Port<0.112526>, \"HTTP/1.1 200 OK\\r\\nserver: Cowboy\\r\\ndate: Wed, 16 Sep 2015 08:43:49 GMT\\r\\ncontent-length: 27\\r\\ncontent-type: application/json\\r\\n\\r\\n{\\n  \\\"origin\\\": \\\"127.0.0.1\\\"\\n}\"}"}
        test/hackney_message_bug_test.exs:31: HackneyMessageBugTest.test_single_download/1
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3


  1) test concurrent downloads of the same URL (HackneyMessageBugTest)
     test/hackney_message_bug_test.exs:41
     ** (EXIT from #PID<0.367.0>) an exception was raised:
         ** (MatchError) no match of right hand side value: {:error, "http://localhost:8080/ip download failed after 1 tries: unexpected message received: {:tcp, #Port<0.112526>, \"HTTP/1.1 200 OK\\r\\nserver: Cowboy\\r\\ndate: Wed, 16 Sep 2015 08:43:49 GMT\\r\\ncontent-length: 27\\r\\ncontent-type: application/json\\r\\n\\r\\n{\\n  \\\"origin\\\": \\\"127.0.0.1\\\"\\n}\"}"}
             test/hackney_message_bug_test.exs:31: HackneyMessageBugTest.test_single_download/1
             (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
             (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3



Finished in 19.3 seconds (0.04s on load, 19.3s on tests)
1 tests, 1 failures

Randomized with seed 613129
```

**Comment by benoitc** [comment]
@flupke hrm i didn't reproduce it yet. Can you tell me which OS you're using?

**Comment by flupke** [comment]
Ubuntu 14.04 with erlang 18

**Comment by benoitc** [comment]
Thanks! ok let's try with an ubuntu then :)

**Comment by flupke** [comment]
I couldn't reproduce this on OSX either, so I tried with Vagrant and didn't reproduce until I upped the number of CPUs for the box in the `Vagrantfile`:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end
end
```

**Comment by flupke** [comment]
Hey, any updates on this issue? Can I help in any way?

**Comment by flupke** [comment]
I read that #276 should fix this issue, so I retried my little experiment with hackney master but the errors are still there.

**Comment by benoitc** [comment]
@flupke i will revisit the way the async worker is working later this week, expect an update over the week-end :)

**Comment by benoitc** [comment]
@flupke do you have any reproducible way to test it btw?

**Comment by flupke** [comment]
Yes, the elixir project above still reproduces it.

Le mer. 5 oct. 2016 à 20:42, Benoit Chesneau <notifications@github.com> a
écrit :

**Comment by benoitc** [comment]
not reproduced .

**Comment by nsweeting** [comment]
This issue occurs for us quite often is test environments using the latest hackney. It will usually occur when:

1. We have an HTTP stream enumerable running using hackney
2. We have an HTTP stream collectable running using hackney

The combination of these two streams running will usually result in:
```
[error] Unexpected message: {:tcp, #Port<0.53>, <<13, 101, 109, 97, 105, 108, 95, 97, 100, 100, 114, 101, 115, 115, 0, 21, 12, 37, 0, 24, 10, 99, 111, 110, 116, 97, 99, 116, 95, 105, 100, 0, 21, 12, 37, 0, 24, 12, 114, 101, 102, 101, 114, 101, 110, 99, 101, ...>>}
```
And an eventual timeout from one of the streams.

**Comment by ftes** [comment]
We are experiencing the same issue as @nsweeting in CI tests (packmatic 1.2.0 -> httpoison 2.2.1 -> hackney 1.20.1).
