### ISSUE TITLE
can't compile hackney with mix

### ISSUE THREAD

**Issue by allyraza** [benoitc/hackney#328]
Hi I am trying to build hackney with httpoison keep getting this

`** (Mix) Could not compile dependency :hackney, "/Users/al-razi/.mix/rebar3 bare compile --paths "/Users/al-razi/work/merchant/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"`

**Comment by ericmj** [comment]
Please include the full output. The actual error was probably a few lines up.

**Comment by allyraza** [comment]
```
iex -S mix
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

===> Compiling idna
===> Compiling mimerl
===> Compiling metrics
==> gettext
Compiling 1 file (.yrl)
Compiling 1 file (.erl)
Compiling 19 files (.ex)
Generated gettext app
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_app.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch.erl
==> poison
Compiling 4 files (.ex)
Generated poison app
===> Compiling ssl_verify_fun
==> combine
Compiling 6 files (.ex)
Generated combine app
===> Compiling certifi
===> Package certifi-0.4.0 not found. Fetching registry updates and trying again...
===> {rebar_prv_update,package_index_write}
==> pay
** (Mix) Could not compile dependency :hackney, "/Users/al-razi/.mix/rebar3 bare compile --paths "/Users/al-razi/work/pay/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"
```

**Comment by ericmj** [comment]
Hard to say what's wrong. Try updating with `mix local.rebar` or run with `DEBUG=1` to see if rebar gives you some more information.

**Comment by allyraza** [comment]
I updated rebar like 5 times before posting an issue

**Comment by benoitc** [comment]
@allyraza which version of hackney?

**Comment by allyraza** [comment]
1.6.0

**Comment by benoitc** [comment]
hrm I don't reproduce it:

````
[hackney] iex -S mix                                                                                                                           14:07:20  ☁  master ☂ ⚡ ✭

Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

==> idna (compile)
Compiled src/punycode.erl
Compiled src/idna_unicode.erl
Compiled src/idna_ucs.erl
Compiled src/idna_unicode_data2.erl
Compiled src/idna.erl
Compiled src/idna_unicode_data1.erl
==> mimerl (compile)
Compiled src/mimerl.erl
==> metrics (compile)
Compiled src/metrics_dummy.erl
Compiled src/metrics_folsom.erl
Compiled src/metrics_exometer.erl
Compiled src/metrics.erl
==> ssl_verify_fun (compile)
Compiled src/ssl_verify_fingerprint.erl
Compiled src/ssl_verify_hostname.erl
==> certifi (compile)
Compiled src/certifi.erl
Compiled src/certifi_cacerts.erl
Compiled src/certifi_weakcerts.erl
Compiled src/hackney_pool_handler.erl
Compiled src/hackney_ssl_transport.erl
Compiled src/hackney_tcp_transport.erl
Compiled src/hackney_connect.erl
Compiled src/hackney_app.erl
Compiled src/hackney_pool.erl
Compiled src/hackney_sup.erl
Compiled src/hackney_http_connect.erl
Compiled src/hackney_cookie.erl
Compiled src/hackney_date.erl
Compiled src/hackney.erl
Compiled src/hackney_url.erl
Compiled src/hackney_stream.erl
Compiled src/hackney_http.erl
Compiled src/hackney_bstr.erl
Compiled src/hackney_manager.erl
Compiled src/hackney_headers.erl
Compiled src/hackney_multipart.erl
Compiled src/hackney_request.erl
Compiled src/hackney_trace.erl
Compiled src/hackney_socks5.erl
Compiled src/hackney_response.erl
Compiled src/hackney_util.erl
Generated hackney app
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
Interactive Elixir (1.2.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
````

or directly with mix: 

```
[hackney] mix deps.get                                                                                                                         14:05:51  ☁  master ☂ ⚡ ✭
Running dependency resolution
* Getting idna (Hex package)
  Checking package (https://repo.hex.pm/tarballs/idna-1.2.0.tar)
  Using locally cached package
* Getting mimerl (Hex package)
  Checking package (https://repo.hex.pm/tarballs/mimerl-1.0.2.tar)
  Using locally cached package
* Getting certifi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/certifi-0.4.0.tar)
  Using locally cached package
* Getting metrics (Hex package)
  Checking package (https://repo.hex.pm/tarballs/metrics-1.0.1.tar)
  Using locally cached package
* Getting ssl_verify_fun (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ssl_verify_fun-1.1.0.tar)
  Using locally cached package
[hackney] DEBUG=1 mix compile                                                                                                                  14:06:01  ☁  master ☂ ⚡ ✭
==> idna (compile)
Compiled src/punycode.erl
Compiled src/idna_unicode_data2.erl
Compiled src/idna_ucs.erl
Compiled src/idna.erl
Compiled src/idna_unicode.erl
Compiled src/idna_unicode_data1.erl
==> mimerl (compile)
Compiled src/mimerl.erl
==> metrics (compile)
Compiled src/metrics_folsom.erl
Compiled src/metrics_dummy.erl
Compiled src/metrics_exometer.erl
Compiled src/metrics.erl
==> ssl_verify_fun (compile)
Compiled src/ssl_verify_fingerprint.erl
Compiled src/ssl_verify_hostname.erl
==> certifi (compile)
Compiled src/certifi.erl
Compiled src/certifi_cacerts.erl
Compiled src/certifi_weakcerts.erl
Generated hackney app
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated IEx.Info
```

**Comment by allyraza** [comment]
okay I will help you reproduce it 
elixir 1.3.0
erlang 18

1. checkout out the following repo https://github.com/era/pay
2. cd into it and run mix deps.get
3. run iex -S mix or just run the tests

**Comment by benoitc** [comment]
@allyraza hrm sorry I couldn't reproduce it either :( It's probably something in your installation. See the log below:

```
[pay] elixir -v                                                                                                         14:42:28  ☁  master ☂ ✭
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

Elixir 1.3.1
[pay] mix deps.get                                                                                                      14:42:31  ☁  master ☂ ✭
Running dependency resolution
* Getting maru (Hex package)
  Checking package (https://repo.hex.pm/tarballs/maru-0.10.2.tar)
  Using locally cached package
* Getting httpoison (Hex package)
  Checking package (https://repo.hex.pm/tarballs/httpoison-0.9.0.tar)
  Using locally cached package
* Getting timex (Hex package)
  Checking package (https://repo.hex.pm/tarballs/timex-2.1.6.tar)
  Using locally cached package
* Getting mock (Hex package)
  Checking package (https://repo.hex.pm/tarballs/mock-0.1.3.tar)
  Using locally cached package
* Getting dogma (Hex package)
  Checking package (https://repo.hex.pm/tarballs/dogma-0.1.7.tar)
  Using locally cached package
* Getting poison (Hex package)
  Checking package (https://repo.hex.pm/tarballs/poison-2.2.0.tar)
  Using locally cached package
* Getting meck (Hex package)
  Checking package (https://repo.hex.pm/tarballs/meck-0.8.4.tar)
  Using locally cached package
* Getting gettext (Hex package)
  Checking package (https://repo.hex.pm/tarballs/gettext-0.11.0.tar)
  Using locally cached package
* Getting combine (Hex package)
  Checking package (https://repo.hex.pm/tarballs/combine-0.9.1.tar)
  Using locally cached package
* Getting tzdata (Hex package)
  Checking package (https://repo.hex.pm/tarballs/tzdata-0.5.8.tar)
  Using locally cached package
* Getting hackney (Hex package)
  Checking package (https://repo.hex.pm/tarballs/hackney-1.6.0.tar)
  Using locally cached package
* Getting ssl_verify_fun (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ssl_verify_fun-1.1.0.tar)
  Using locally cached package
* Getting mimerl (Hex package)
  Checking package (https://repo.hex.pm/tarballs/mimerl-1.0.2.tar)
  Using locally cached package
* Getting metrics (Hex package)
  Checking package (https://repo.hex.pm/tarballs/metrics-1.0.1.tar)
  Using locally cached package
* Getting idna (Hex package)
  Checking package (https://repo.hex.pm/tarballs/idna-1.2.0.tar)
  Using locally cached package
* Getting certifi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/certifi-0.4.0.tar)
  Using locally cached package
* Getting plug (Hex package)
  Checking package (https://repo.hex.pm/tarballs/plug-1.1.6.tar)
  Using locally cached package
* Getting cowboy (Hex package)
  Checking package (https://repo.hex.pm/tarballs/cowboy-1.0.4.tar)
  Using locally cached package
* Getting cowlib (Hex package)
  Checking package (https://repo.hex.pm/tarballs/cowlib-1.0.2.tar)
  Using locally cached package
* Getting ranch (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ranch-1.2.1.tar)
  Using locally cached package
[pay] mix test                                                                                                          14:42:41  ☁  master ☂ ✭
===> Compiling idna
===> Compiling mimerl
===> Compiling metrics
==> gettext
Compiling 1 file (.yrl)
Compiling 1 file (.erl)
Compiling 19 files (.ex)
Generated gettext app
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_app.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch.erl
==> meck (compile)
Compiled src/meck_util.erl
Compiled src/meck_ret_spec.erl
Compiled src/meck_proc.erl
Compiled src/meck_matcher.erl
Compiled src/meck_history.erl
Compiled src/meck_expect.erl
Compiled src/meck_cover.erl
Compiled src/meck_args_matcher.erl
Compiled src/meck_code.erl
Compiled src/meck_code_gen.erl
Compiled src/meck.erl
warning: undefined module attribute @version, please remove access to @version or explicitly set it before access
  mix.exs:12: Mock.Mixfile.project/0

==> mock
Compiling 1 file (.ex)
Generated mock app
==> poison
Compiling 4 files (.ex)
Generated poison app
===> Compiling ssl_verify_fun
==> combine
Compiling 6 files (.ex)
Generated combine app
===> Compiling certifi
===> Compiling hackney
==> tzdata
Compiling 16 files (.ex)
Generated tzdata app
==> timex
Compiling 53 files (.ex)
warning: unused import Combine.Parsers.Base.sequence/1
  lib/parse/datetime/parser.ex:5

warning: function Timex.Date.weekday/1 is undefined or private
Found at 2 locations:
  lib/parse/datetime/parser.ex:192
  lib/parse/datetime/parser.ex:199

warning: function Timex.Calendar.is_leap_year?/1 is undefined or private
  lib/calendar/gregorian.ex:23

Generated timex app
==> httpoison
Compiling 2 files (.ex)
Generated httpoison app
==> cowlib (compile)
Compiled src/cow_qs.erl
Compiled src/cow_spdy.erl
Compiled src/cow_multipart.erl
Compiled src/cow_http_te.erl
Compiled src/cow_http_hd.erl
Compiled src/cow_date.erl
Compiled src/cow_http.erl
Compiled src/cow_cookie.erl
Compiled src/cow_mimetypes.erl
==> cowboy (compile)
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_websocket_handler.erl
Compiled src/cowboy_static.erl
Compiled src/cowboy_spdy.erl
Compiled src/cowboy_router.erl
Compiled src/cowboy_websocket.erl
Compiled src/cowboy_rest.erl
Compiled src/cowboy_loop_handler.erl
Compiled src/cowboy_http_handler.erl
Compiled src/cowboy_protocol.erl
Compiled src/cowboy_handler.erl
Compiled src/cowboy_clock.erl
Compiled src/cowboy_bstr.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy_req.erl
Compiled src/cowboy.erl
Compiled src/cowboy_http.erl
==> plug
Compiling 44 files (.ex)
Generated plug app
==> maru
Compiling 49 files (.ex)
warning: function Mix.Phoenix.base/0 is undefined (module Mix.Phoenix is not available)
  lib/mix/tasks/routes.ex:27

Generated maru app
==> pay
Compiling 6 files (.ex)
warning: variable pid is unused
  lib/paypal/app.ex:8

Generated pay app
warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
.warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
.warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
warning: Timex.Time.to_secs/1 is deprecated, use to_seconds/1 instead
..

Finished in 0.2 seconds
4 tests, 0 failures

Randomized with seed 157294
[pay]                                                                                                                   14:43:19  ☁  master ☂ ✭
```

**Comment by allyraza** [comment]
well I uninstalled elixir, erlang and setup a new mix project issue still persists

**Comment by ericmj** [comment]
Do you update rebar with `mix local.rebar`?

On Fri, Jul 1, 2016 at 4:12 PM, al-razi <notifications@github.com> wrote:

> well I uninstalled elixir, erlang and setup a new mix project issue still
> persists
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/benoitc/hackney/issues/328#issuecomment-229957291>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2qb1jdDAi2SLf6BlKFwAM9Q0kLKeks5qRSA6gaJpZM4JCvdC>
> .
>



-- 
Eric Meadows-Jönsson

**Comment by allyraza** [comment]
yes I did

**Comment by allyraza** [comment]
I guess this has to do with rebar


```
Error creating package index: {badmatch,{error,enoent}} [{rebar_packages,
                                                               registry_dir,1,
                                                               [{file,
                                                                 "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_packages.erl"},
                                                                {line,99}]},
                                                              {rebar_prv_update,
                                                               do,1,
                                                               [{file,
                                                                 "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_update.erl"},
                                                                {line,43}]},
                                                              {rebar_packages,
                                                               handle_missing_package,
                                                               3,
                                                               [{file,
                                                                 "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_packages.erl"},
                                                                {line,85}]},
                                                              {rebar_app_utils,
                                                               update_source,
                                                               3,
                                                               [{file,
                                                                 "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                                {line,189}]},
                                                              {rebar_app_utils,
                                                               dep_to_app,7,
                                                               [{file,
                                                                 "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                                {line,167}]},
                                                              {rebar_app_utils,
                                                               '-parse_deps/6-lc$^0/1-0-',
                                                               6,
                                                               [{file,
                                                                 "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                                {line,98}]},
                                                              {rebar_app_discover,
                                                               '-do/2-fun-0-',
                                                               3,
                                                               [{file,
                                                                 "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                                                                {line,31}]},
                                                              {lists,foldl,3,
                                                               [{file,
                                                                 "lists.erl"},
                                                                {line,1262}]}]
===> {rebar_prv_update,package_index_write}
```

**Comment by allyraza** [comment]
why is it going to `/home/tristan/Devel/rebar3/_build/`

**Comment by allyraza** [comment]
I don't have that directory

**Comment by ericmj** [comment]
It's just where the source files were located when rebar was built.

On Fri, Jul 1, 2016 at 4:20 PM, al-razi <notifications@github.com> wrote:

> I don't have that directory
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/benoitc/hackney/issues/328#issuecomment-229959385>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2nsQu9Y37Wp8SHBjZYcVX_H8BjNIks5qRSI8gaJpZM4JCvdC>
> .
>



-- 
Eric Meadows-Jönsson

**Comment by lukeed** [comment]
I had this while trying to compile [HTTPoison](https://github.com/edgurgel/httpoison) v0.9.0, using Hackney 1.6.

The `mix local.rebar` worked for me, thanks!

Before that, I updated my erlang & elixir (and therefore mix) packages via brew. I'm not running 1.3.2 & everything is compiling smoothly.

**Comment by rubencaro** [comment]
`mix local.rebar` worked for me too!

**Comment by gmile** [comment]
I have been seeing the issue for a few days as well. `mix local.rebar` helped, thanks!

**Comment by miskolc** [comment]
mix local.rebar worked for me three!

**Comment by benoitc** [comment]
should be fixed with latest version of mix.

**Comment by ajvondrak** [comment]
This is still happening for me. 😕

```
/tmp$ brew info elixir
elixir: stable 1.3.2 (bottled), HEAD
Functional metaprogramming aware language built on Erlang VM
http://elixir-lang.org/
/usr/local/Cellar/elixir/1.3.2 (383 files, 5M) *
  Poured from bottle on 2016-08-30 at 15:30:26
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/elixir.rb
```

```
/tmp$ mix -v
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Mix 1.3.2
```

```
/tmp$ mix new repro
* creating README.md
* creating .gitignore
* creating mix.exs
* creating config
* creating config/config.exs
* creating lib
* creating lib/repro.ex
* creating test
* creating test/test_helper.exs
* creating test/repro_test.exs

Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:

    cd repro
    mix test

Run "mix help" for more commands.
```

```
/tmp$ cd repro
/tmp/repro$ git init && git add . && git commit -m 'Initial commit'
Initialized empty Git repository in /private/tmp/repro/.git/
[master (root-commit) 7f15e42] Initial commit
 7 files changed, 114 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 README.md
 create mode 100644 config/config.exs
 create mode 100644 lib/repro.ex
 create mode 100644 mix.exs
 create mode 100644 test/repro_test.exs
 create mode 100644 test/test_helper.exs
```

```
/tmp/repro$ vim mix.exs
/tmp/repro$ git diff
diff --git a/mix.exs b/mix.exs
index 094874c..144eff5 100644
--- a/mix.exs
+++ b/mix.exs
@@ -27,6 +27,6 @@ defmodule Repro.Mixfile do
   #
   # Type "mix help deps" for more examples and options
   defp deps do
-    []
+    [{:hackney, "~> 1.6.1"}]
   end
 end
```

```
/tmp/repro$ mix do deps.get, deps.compile
Running dependency resolution
Dependency resolution completed
  certifi: 0.4.0
  hackney: 1.6.1
  idna: 1.2.0
  metrics: 1.0.1
  mimerl: 1.0.2
  ssl_verify_fun: 1.1.0
* Getting hackney (Hex package)
  Checking package (https://repo.hex.pm/tarballs/hackney-1.6.1.tar)
  Using locally cached package
* Getting certifi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/certifi-0.4.0.tar)
  Using locally cached package
* Getting idna (Hex package)
  Checking package (https://repo.hex.pm/tarballs/idna-1.2.0.tar)
  Using locally cached package
* Getting metrics (Hex package)
  Checking package (https://repo.hex.pm/tarballs/metrics-1.0.1.tar)
  Using locally cached package
* Getting mimerl (Hex package)
  Checking package (https://repo.hex.pm/tarballs/mimerl-1.0.2.tar)
  Using locally cached package
* Getting ssl_verify_fun (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ssl_verify_fun-1.1.0.tar)
  Using locally cached package
===> Compiling idna
===> Compiling mimerl
===> Compiling metrics
===> Compiling ssl_verify_fun
===> Compiling certifi
===> Package certifi-0.4.0 not found. Fetching registry updates and trying again...
===> {rebar_prv_update,package_index_write}
** (Mix) Could not compile dependency :hackney, "/Users/avondrak/.mix/rebar3 bare compile --paths "/private/tmp/repro/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"
```

```
/tmp/repro$ ~/.mix/rebar3 -v
rebar 3.2.0 on Erlang/OTP 19 Erts 8.0.2
/tmp/repro$ mix local.rebar
/Users/avondrak/.mix/rebar already exists, overwrite? [Yn] Y
* creating /Users/avondrak/.mix/rebar
/Users/avondrak/.mix/rebar3 already exists, overwrite? [Yn] Y
* creating /Users/avondrak/.mix/rebar3
/tmp/repro$ ~/.mix/rebar3 -v
rebar 3.2.0 on Erlang/OTP 19 Erts 8.0.2
```

```
/tmp/repro$ DEBUG=1 /Users/avondrak/.mix/rebar3 bare compile --paths "/private/tmp/repro/_build/dev/lib/*/ebin"
===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {bare,compile}]
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,[]}
===> Stack trace to the error location: [{rebar_prv_bare_compile,do,1,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_bare_compile.erl"},
                                                  {line,45}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar_prv_do,do_tasks,2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                                                  {line,68}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar3,main,1,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
                                                  {line,56}]},
                                                {escript,run,2,
                                                 [{file,"escript.erl"},
                                                  {line,757}]},
                                                {escript,start,1,
                                                 [{file,"escript.erl"},
                                                  {line,277}]},
                                                {init,start_em,1,[]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
```

```
/tmp/repro$ DEBUG=1 /Users/avondrak/.mix/rebar3 report 'bare compile --paths "/private/tmp/repro/_build/dev/lib/*/ebin"'
===> Expanded command sequence to be run: [{default,report}]
Rebar3 report
 version 3.2.0
 generated at 2016-09-06T23:22:15+00:00
=================
Please submit this along with your issue at https://github.com/erlang/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: bare
Entered as:
  bare compile --paths "/private/tmp/repro/_build/dev/lib/*/ebin"
-----------------
Operating System: x86_64-apple-darwin13.4.0
ERTS: Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]
Root Directory: /usr/local/Cellar/erlang/19.0.2/lib/erlang
Library directory: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.0.4
certifi: 0.4.0
cf: 0.2.1
common_test: 1.12.2
compiler: 7.0.1
crypto: 3.7
cth_readable: 1.2.2
dialyzer: 3.0.1
edoc: 0.7.19
erlware_commons: 0.21.0
eunit: 2.3
eunit_formatters: 0.3.1
getopt: 0.8.2
inets: 6.3.1
kernel: 5.0
providers: 1.6.0
public_key: 1.2
relx: 3.19.0
sasl: 3.0
snmp: 5.2.3
ssl_verify_hostname: 1.0.5
stdlib: 3.0.1
syntax_tools: 2.0
tools: 2.8.5

-----------------
Escript path: /Users/avondrak/.mix/rebar3
Providers:
  app_discovery as clean compile compile cover ct deps dialyzer do edoc escriptize eunit help install install_deps list lock new path pkgs release relup report shell state tar tree unlock update upgrade upgrade upgrade version xref
```

Any ideas?

**Comment by MVilstrup** [comment]
I'm having the same problem as ajvondrak. Whenever I run mix test it says: 

> ===> Package certifi-0.4.0 not found. Fetching registry updates and trying again...
> ===> {rebar_prv_update,package_index_write}
> ** (Mix) Could not compile dependency :hackney, "/Users/Vilstrup/.mix/rebar3 bare compile --paths "/Users/Vilstrup/Code/elixir/exchat/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"

And when I run the command with DEBUG=1 I get:

`===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {bare,compile}]
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,[]}
===> Stack trace to the error location: [{rebar_prv_bare_compile,do,1,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_bare_compile.erl"},
                                                  {line,45}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar_prv_do,do_tasks,2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                                                  {line,68}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar3,main,1,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
                                                  {line,56}]},
                                                {escript,run,2,
                                                 [{file,"escript.erl"},
                                                  {line,757}]},
                                                {escript,start,1,
                                                 [{file,"escript.erl"},
                                                  {line,277}]},
                                                {init,start_em,1,[]}]`

**Comment by lukeed** [comment]
@ajvondrak @MVilstrup Did you both try `mix local.rebar` ? That seems to be the fix for everyone.

**Comment by MVilstrup** [comment]
Yes. I have tried several times, but it does not change anything :)

**Comment by ajvondrak** [comment]
@lukeed Afraid so, as seen in my prior comment (and why I thought it necessary to point out):

```
/tmp/repro$ ~/.mix/rebar3 -v
rebar 3.2.0 on Erlang/OTP 19 Erts 8.0.2
/tmp/repro$ mix local.rebar
/Users/avondrak/.mix/rebar already exists, overwrite? [Yn] Y
* creating /Users/avondrak/.mix/rebar
/Users/avondrak/.mix/rebar3 already exists, overwrite? [Yn] Y
* creating /Users/avondrak/.mix/rebar3
/tmp/repro$ ~/.mix/rebar3 -v
rebar 3.2.0 on Erlang/OTP 19 Erts 8.0.2
```

I also do not have a separate `rebar3` on my PATH, as in [this issue](https://github.com/elixir-lang/elixir/issues/4970).

One thing I notice is that rebar 3.2.0 does not seem to be the latest version, which on https://www.rebar3.org/ is 3.3.1. Is Mix's CDN out of date, or is 3.2.0 intentional?

**Comment by ajvondrak** [comment]
Meh, still no dice with rebar 3.3.1 :-/

```
/tmp/repro$ mix local.rebar rebar3 https://s3.amazonaws.com/rebar3/rebar3
/Users/avondrak/.mix/rebar3 already exists, overwrite? [Yn] Y
* creating /Users/avondrak/.mix/rebar3
/tmp/repro$ ~/.mix/rebar3 -v
rebar 3.3.1 on Erlang/OTP 19 Erts 8.0.2
/tmp/repro$ mix do deps.get, deps.compile
Running dependency resolution
All dependencies up to date
===> Compiling idna
===> Compiling mimerl
===> Compiling metrics
===> Compiling ssl_verify_fun
===> Compiling certifi
===> Package certifi-0.4.0 not found. Fetching registry updates and trying again...
===> {rebar_prv_update,package_index_write}
** (Mix) Could not compile dependency :hackney, "/Users/avondrak/.mix/rebar3 bare compile --paths "/private/tmp/repro/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"
```

**Comment by ajvondrak** [comment]
@MVilstrup After enough issue browsing, I seem to have fixed my local build.

- https://github.com/benoitc/hackney/issues/341 indicates you need to run `~/.mix/rebar3 update`, which was failing with the same error for me
- so I started googling around for rebar3 issues with the `package_index_write` error being thrown, which landed me on https://github.com/erlang/rebar3/issues/1296

It turns out on OSX that my `~/.cache` directory is owned by root, and the directory `~/.cache/rebar3` did not exist. The error was thus being thrown when rebar3 failed to write the package index to `~/.cache/rebar3/hex/default/packages.idx` because it didn't have the permissions to create the directory.

So, I created the `~/.cache/rebar3` directory and changed the owner to be the same one used for `mix`:

```
$ sudo mkdir ~/.cache/rebar3
$ sudo chown $USER ~/.cache/rebar3
```

(I suspect the whole `~/.cache` directory should just be owned by me, but...) Now compilation works on my machine:

```
/tmp/repro$ mix do deps.get, deps.compile
Running dependency resolution
Dependency resolution completed
  certifi: 0.4.0
  hackney: 1.6.1
  idna: 1.2.0
  metrics: 1.0.1
  mimerl: 1.0.2
  ssl_verify_fun: 1.1.0
* Getting hackney (Hex package)
  Checking package (https://repo.hex.pm/tarballs/hackney-1.6.1.tar)
  Using locally cached package
* Getting certifi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/certifi-0.4.0.tar)
  Using locally cached package
* Getting idna (Hex package)
  Checking package (https://repo.hex.pm/tarballs/idna-1.2.0.tar)
  Using locally cached package
* Getting metrics (Hex package)
  Checking package (https://repo.hex.pm/tarballs/metrics-1.0.1.tar)
  Using locally cached package
* Getting mimerl (Hex package)
  Checking package (https://repo.hex.pm/tarballs/mimerl-1.0.2.tar)
  Using locally cached package
* Getting ssl_verify_fun (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ssl_verify_fun-1.1.0.tar)
  Using locally cached package
===> Compiling idna
===> Compiling mimerl
===> Compiling metrics
===> Compiling ssl_verify_fun
===> Compiling certifi
===> Package certifi-0.4.0 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /Users/avondrak/.cache/rebar3/hex/default/registry
===> Generating package index...
===> [cloudi_service_oauth1:1.5.1] Only existing version of cloudi_service_db_riak is 1.3.3 which does not match constraint ~> 1.5.1. Using anyway, but it is not guaranteed to work.
===> Writing index to /Users/avondrak/.cache/rebar3/hex/default/packages.idx
===> Compiling hackney
src/hackney_pool.erl:213: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

src/hackney_multipart.erl:271: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
```

:tada:

:warning: You should **not** just run `sudo mix deps.compile`. This works initially, but running as root means that even directories local to your project get created with root as the owner. This can screw up subsequent non-root runs of `mix` tasks, which I learned during an early "quick & dirty" attempt to verify the permissions issue:

```
/tmp/repro$ mix deps.clean --all --unlock
* Cleaning hackney
** (File.Error) could not remove files and directories recursively from "/private/tmp/repro/deps/hackney": permission denied
    (elixir) lib/file.ex:919: File.rm_rf!/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/tasks/deps.clean.ex:53: Mix.Tasks.Deps.Clean.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Hope that helps.

**Comment by MVilstrup** [comment]
Thank you @ajvondrak! I turned out to have the exact same problem. Your solution fixed it on my computer as well 👍 👍

**Comment by drozzy** [comment]
I'm getting the same error. When I try to compile a project in CentOS7 that depends on `ssl_verify_fun` as follows:

```
 defp deps do
      [  {:ssl_verify_fun, ">= 0.0.0"} ]
    end
```
Trying to run compile gives me this rather strange error:

```
$ mix compile
escript: exception error: undefined function rebar:main/1
  in function  escript:run/2 (escript.erl, line 757)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
** (Mix) Could not compile dependency :ssl_verify_fun, "/home/drozdyuka/.mix/rebar compile skip_deps=true deps_dir="/projects/proj/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile ssl_verify_fun", update it with "mix deps.update ssl_verify_fun" or clean it with "mix deps.clean ssl_verify_fun"


```

**Comment by drozzy** [comment]
Nevermind, `mix local.rebar` fixed it.

I was using the long form before `mix local.rebar rebar rebar3` - that didn't work.

**Comment by evidsibi** [comment]
Hi am having a similar issue. tried all the above fixes gen_smtp always throws and error when compiling 

** (Mix) Could not compile dependency :gen_smtp, "/home/ubuntu/.mix/rebar3 bare compile --paths "/apps/eresident/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile gen_smtp", update it with "mix deps.update gen_smtp" or clean it with "mix deps.clean gen_smtp"

When I checked the rebar.crashdump file I got the following error.

Error: undef
[{yecc,file,
       ["/apps/eresident/deps/gen_smtp/src/smtp_rfc822_parse.yrl",
        [{return,true}]],
       []},
 {rebar_erlc_compiler,compile_xrl_yrl,5,
                      [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_erlc_compiler.erl"},
                       {line,590}]},
 {rebar_base_compiler,compile_each,3,
                      [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_base_compiler.erl"},
                       {line,134}]},
 {rebar_erlc_compiler,compile,2,
                      [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_erlc_compiler.erl"},
                       {line,109}]},
 {rebar_prv_compile,compile,3,
                    [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_compile.erl"},
                     {line,122}]},
 {rebar_prv_bare_compile,do,1,
                         [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_bare_compile.erl"},
                          {line,47}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,125}]},
 {rebar_prv_do,do_tasks,2,
               [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                {line,68}]}]

**Comment by benoitc** [comment]
@evidsibi imho this issue is not related to hackney but with mix. Did you check with their developers?

**Comment by evidsibi** [comment]
@benoitc raised it with them

**Comment by arteepa** [comment]
`~/.mix/rebar3 update` did it for me.

**Comment by fertapric** [comment]
In my case, I fixed it by instaling `erlang-parsetools`.  I was building a Docker container based on `alpine:3.6`. Hope it helps!

**Comment by andersondanilo** [comment]
Me too (with Elixir 1.6.3 OTP 20)

**Comment by mjsommer** [comment]
@allyraza , I downloaded your https://github.com/era/pay.git, and received the same `Compiling src/hackney_ssl.erl failed` issue when compiling. Were you ever able to resolve this, and if so, how?

**Comment by benoitc** [comment]
> @allyraza , I downloaded your https://github.com/era/pay.git, and received the same `Compiling src/hackney_ssl.erl failed` issue when compiling. Were you ever able to resolve this, and if so, how?

please open a new issue if you are experimenting some problem, and please paste the whole log. You may want to test latest master anyway.

**Comment by mjsommer** [comment]
> > @allyraza , I downloaded your https://github.com/era/pay.git, and received the same `Compiling src/hackney_ssl.erl failed` issue when compiling. Were you ever able to resolve this, and if so, how?
> 
> please open a new issue if you are experimenting some problem, and please paste the whole log. You may want to test latest master anyway.

Ref: https://github.com/era/pay/issues/18
